version: "3.9"

services:
     card:
          image: card
          ports: 
               - "8082:8082"
     deck:
          image: deck
          ports:
               - "8080:8080"
     fileio:
          image: fileio
          ports: 
               - "8081:8081"

     romme:
          image: romme