version: "3.9"

services:
     card:
          image: card
          stdin_open: true
          tty: true
          read_only: false
          container_name: card
          ports: 
               - "8082:8082"
     deck:
          image: deck
          stdin_open: true
          tty: true
          read_only: false
          container_name: deck
          ports:
               - "8080:8080"
          depends_on:
               - card
     fileio:
          image: fileio
          ports: 
               - "8081:8081"
          stdin_open: true
          tty: true
          read_only: false
          container_name: fileio            
          depends_on:
               - deck
               - card
          
