version: "3.9"

services:

  fileio:
    image: fileio
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true
    container_name: romme-fileio-service
    environment:
      FILEIO_SERVICE_HOST: romme-fileio-service
      FILEIO_SERVICE_PORT: 8082
    working_dir: /fileIO
    volumes:
      - ./:/fileio:xro

  card:
    image: card
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    container_name: romme-card-service
    environment:
      CARD_SERVICE_HOST: romme-card-service
      CARD_SERVICE_PORT: 8080

  deck:
    image: deck
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    container_name: romme-deck-service
    depends_on:
        - card
    environment:
      DECK_SERVICE_HOST: romme-deck-service
      DECK_SERVICE_PORT: 8081
    working_dir: /deck
    volumes:
      - ./:/deck:xro

  romme:
    image: romme:0.1.0-SNAPSHOT
    ports:
      - "8083:8083"
    stdin_open: true
    tty: true
    read_only: false
    container_name: romme_service
    depends_on:
      - card
      - deck
      - fileio
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      ROMME_SERVICE_HOST: romme
      ROMME_SERVICE_PORT: 8083
      FILEIO_SERVICE_HOST: romme-fileio-service
      FILEIO_SERVICE_PORT: 8082
      CARD_SERVICE_HOST: romme-card-service
      CARD_SERVICE_PORT: 8080
      DECK_SERVICE_HOST: romme-deck-service
      DECK_SERVICE_PORT: 8081